"""init schema baseline

Revision ID: 493e9553e224
Revises: 
Create Date: 2026-06-02 16:58:23.421314+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '493e9553e224'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('contract_addr', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['real_estates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_contract_id'), 'analyses', ['contract_id'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_owner_id'), 'analyses', ['owner_id'], unique=False)
    op.create_table('analysis_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('s3_url', sa.String(length=1024), nullable=False),
    sa.Column('group_type', sa.String(length=16), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('ai_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('damage_type', sa.String(length=64), nullable=True),
    sa.Column('part', sa.String(length=255), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True),
    sa.Column('total_repair_cost', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('tenant_cost', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('depreciation_rate', sa.Float(), nullable=True),
    sa.Column('useful_life_years', sa.Float(), nullable=True),
    sa.Column('elapsed_years', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_photos_analysis_id'), 'analysis_photos', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_photos_celery_task_id'), 'analysis_photos', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_analysis_photos_file_hash'), 'analysis_photos', ['file_hash'], unique=False)
    op.create_index(op.f('ix_analysis_photos_id'), 'analysis_photos', ['id'], unique=False)
    op.create_table('analysis_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['analysis_photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_messages_analysis_id'), 'analysis_messages', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_messages_id'), 'analysis_messages', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_messages_photo_id'), 'analysis_messages', ['photo_id'], unique=False)
    # repair_estimates는 damage_images에 FK 의존 → 자식부터 drop.
    op.drop_index('ix_repair_estimates_celery_task_id', table_name='repair_estimates')
    op.drop_index('ix_repair_estimates_damage_image_id', table_name='repair_estimates')
    op.drop_index('ix_repair_estimates_id', table_name='repair_estimates')
    op.drop_index('ix_repair_estimates_image_hash', table_name='repair_estimates')
    op.drop_index('ix_repair_estimates_real_estate_created', table_name='repair_estimates')
    op.drop_index('ix_repair_estimates_real_estate_id', table_name='repair_estimates')
    op.drop_table('repair_estimates')
    op.drop_index('ix_damage_images_file_hash', table_name='damage_images')
    op.drop_index('ix_damage_images_id', table_name='damage_images')
    op.drop_index('ix_damage_images_real_estate_id', table_name='damage_images')
    op.drop_table('damage_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_estimates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('real_estate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('damage_image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_repair_cost', sa.NUMERIC(precision=12, scale=0), autoincrement=False, nullable=False),
    sa.Column('useful_life_years', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('elapsed_years', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tenant_cost', sa.NUMERIC(precision=12, scale=0), autoincrement=False, nullable=False),
    sa.Column('depreciation_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('part', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('damage_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('estimated_cost', sa.NUMERIC(precision=12, scale=0), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('image_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('analysis_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('celery_task_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['damage_image_id'], ['damage_images.id'], name='repair_estimates_damage_image_id_fkey'),
    sa.ForeignKeyConstraint(['real_estate_id'], ['real_estates.id'], name='repair_estimates_real_estate_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='repair_estimates_pkey')
    )
    op.create_index('ix_repair_estimates_real_estate_id', 'repair_estimates', ['real_estate_id'], unique=False)
    op.create_index('ix_repair_estimates_real_estate_created', 'repair_estimates', ['real_estate_id', 'created_at'], unique=False)
    op.create_index('ix_repair_estimates_image_hash', 'repair_estimates', ['image_hash'], unique=False)
    op.create_index('ix_repair_estimates_id', 'repair_estimates', ['id'], unique=False)
    op.create_index('ix_repair_estimates_damage_image_id', 'repair_estimates', ['damage_image_id'], unique=False)
    op.create_index('ix_repair_estimates_celery_task_id', 'repair_estimates', ['celery_task_id'], unique=False)
    op.create_table('damage_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('real_estate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s3_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('damage_type', postgresql.ENUM('wallpaper', 'floor', 'other', name='damage_type_enum'), autoincrement=False, nullable=False),
    sa.Column('ai_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['real_estate_id'], ['real_estates.id'], name='damage_images_real_estate_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='damage_images_pkey')
    )
    op.create_index('ix_damage_images_real_estate_id', 'damage_images', ['real_estate_id'], unique=False)
    op.create_index('ix_damage_images_id', 'damage_images', ['id'], unique=False)
    op.create_index('ix_damage_images_file_hash', 'damage_images', ['file_hash'], unique=False)
    op.drop_index(op.f('ix_analysis_messages_photo_id'), table_name='analysis_messages')
    op.drop_index(op.f('ix_analysis_messages_id'), table_name='analysis_messages')
    op.drop_index(op.f('ix_analysis_messages_analysis_id'), table_name='analysis_messages')
    op.drop_table('analysis_messages')
    op.drop_index(op.f('ix_analysis_photos_id'), table_name='analysis_photos')
    op.drop_index(op.f('ix_analysis_photos_file_hash'), table_name='analysis_photos')
    op.drop_index(op.f('ix_analysis_photos_celery_task_id'), table_name='analysis_photos')
    op.drop_index(op.f('ix_analysis_photos_analysis_id'), table_name='analysis_photos')
    op.drop_table('analysis_photos')
    op.drop_index(op.f('ix_analyses_owner_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_contract_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
